[character]
# Replace the 'â¯' with 'âœ' if you prefer
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[package]
disabled = true

[git_branch]
style = "bold purple"
symbol = "ğŸŒ± "

[golang]
style = "bold cyan"
symbol = "ğŸ¹ "

[custom.flutter]
command = "flutter --version | head -n 1 | awk '{print $2}'"
when = "test -f pubspec.yaml"
symbol = "ğŸ’™ "
style = "bold blue"
